name: Scheduled Lighthouse Reports

on:
  schedule:
    - cron: "0 10 * * *"  # run every day at 10:00 AM UTC
  workflow_dispatch:      # allow manual run

jobs:
  run-lighthouse:
    runs-on: ubuntu-latest

    # ✅ Restrict workflow to only run when the branch is main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Lighthouse automation
        run: npm run all:lighthouse

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Switch to auto-daily-report branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/auto-daily-report; then
            git checkout auto-daily-report
          else
            git checkout --orphan auto-daily-report
            git rm -rf . > /dev/null 2>&1 || true
            git commit --allow-empty -m "chore: initialize auto-daily-report branch [skip ci]"
            git push origin auto-daily-report
          fi

      - name: Update branch with latest changes
        run: git pull origin auto-daily-report --rebase || true

      - name: Copy new reports into branch
        run: |
          cp -r reports/* . || echo "No reports to copy"

      - name: Commit & push reports
        run: |
          git add .
          git commit -m "chore: add Lighthouse reports [skip ci]" || echo "No changes"
          git push origin auto-daily-report